-- AlterTable: change DELIVERED to RECEIVED in ParcelStatus enum
ALTER TABLE `Parcel` MODIFY COLUMN `status` ENUM('PENDING', 'IN_TRANSIT', 'RECEIVED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
