/**
 * Lightweight database migration runner for cPanel shared hosting.
 *
 * Replaces `prisma migrate deploy` which requires too much memory (WASM engine)
 * for shared hosting environments. This script reads the SQL files generated by
 * Prisma and executes them directly using the mariadb driver.
 *
 * Usage:  node scripts/migrate.js
 * cPanel: Run JS Script → migrate
 */

const mariadb = require('mariadb');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const MIGRATIONS_DIR = path.join(__dirname, '..', 'prisma', 'migrations');
const MIGRATIONS_TABLE = '_prisma_migrations';

function parseDatabaseUrl(url) {
    const parsed = new URL(url);
    return {
        host: parsed.hostname,
        port: parsed.port ? Number(parsed.port) : 3306,
        user: decodeURIComponent(parsed.username),
        password: decodeURIComponent(parsed.password),
        database: parsed.pathname.replace(/^\//, ''),
        multipleStatements: true,
    };
}

async function ensureMigrationsTable(conn) {
    await conn.query(`
    CREATE TABLE IF NOT EXISTS \`${MIGRATIONS_TABLE}\` (
      \`id\` VARCHAR(36) NOT NULL,
      \`checksum\` VARCHAR(64) NOT NULL,
      \`finished_at\` DATETIME(3),
      \`migration_name\` VARCHAR(255) NOT NULL,
      \`logs\` TEXT,
      \`rolled_back_at\` DATETIME(3),
      \`started_at\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      \`applied_steps_count\` INT UNSIGNED NOT NULL DEFAULT 0,
      PRIMARY KEY (\`id\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  `);
}

async function getAppliedMigrations(conn) {
    const rows = await conn.query(
        `SELECT migration_name FROM \`${MIGRATIONS_TABLE}\` WHERE rolled_back_at IS NULL ORDER BY migration_name`
    );
    return new Set(rows.map((r) => r.migration_name));
}

function getPendingMigrations(appliedSet) {
    if (!fs.existsSync(MIGRATIONS_DIR)) {
        return [];
    }

    return fs
        .readdirSync(MIGRATIONS_DIR)
        .filter((name) => {
            const migrationSql = path.join(MIGRATIONS_DIR, name, 'migration.sql');
            return fs.existsSync(migrationSql) && !appliedSet.has(name);
        })
        .sort();
}

function generateId() {
    return crypto.randomUUID();
}

function checksum(content) {
    return crypto.createHash('sha256').update(content).digest('hex');
}

async function applyMigration(conn, migrationName) {
    const sqlPath = path.join(MIGRATIONS_DIR, migrationName, 'migration.sql');
    const sql = fs.readFileSync(sqlPath, 'utf-8');
    const hash = checksum(sql);
    const id = generateId();

    // Record migration as started
    await conn.query(
        `INSERT INTO \`${MIGRATIONS_TABLE}\` (id, checksum, migration_name, started_at, applied_steps_count)
     VALUES (?, ?, ?, NOW(3), 0)`,
        [id, hash, migrationName]
    );

    try {
        // Execute the migration SQL (convert CREATE TABLE to IF NOT EXISTS for safety)
        const safeSql = sql.replace(/CREATE TABLE `/g, 'CREATE TABLE IF NOT EXISTS `');
        await conn.query(safeSql);

        // Mark as finished
        await conn.query(
            `UPDATE \`${MIGRATIONS_TABLE}\` SET finished_at = NOW(3), applied_steps_count = 1 WHERE id = ?`,
            [id]
        );

        console.log(`  ✅ ${migrationName}`);
    } catch (err) {
        // Log the error in the migrations table
        await conn.query(
            `UPDATE \`${MIGRATIONS_TABLE}\` SET logs = ? WHERE id = ?`,
            [err.message, id]
        );
        throw err;
    }
}

async function main() {
    const databaseUrl = process.env.DATABASE_URL;

    if (!databaseUrl) {
        console.error('❌ DATABASE_URL environment variable is not set.');
        process.exit(1);
    }

    let conn;
    try {
        const config = parseDatabaseUrl(databaseUrl);
        conn = await mariadb.createConnection(config);

        console.log('🔌 Connected to database\n');

        await ensureMigrationsTable(conn);

        const applied = await getAppliedMigrations(conn);
        const pending = getPendingMigrations(applied);

        if (pending.length === 0) {
            console.log('✅ No pending migrations. Database is up to date.');
            return;
        }

        console.log(`📦 ${pending.length} pending migration(s):\n`);

        for (const migration of pending) {
            await applyMigration(conn, migration);
        }

        console.log('\n✅ All migrations applied successfully!');
    } catch (err) {
        console.error('\n❌ Migration failed:', err.message);
        process.exit(1);
    } finally {
        if (conn) await conn.end();
    }
}

main();
